### ISSUE TITLE
Error on first run of rake after setup

### ISSUE THREAD

**Issue by crawfoal** [rubyforgood/habitat_humanity#105]
When I first ran `bundle exec rake` after running the setup script, I got an error saying that the test database didn't exist:

```
FATAL:  database "habitat_humanity_test" does not exist (ActiveRecord::NoDatabaseError)
```

To fix this, I ran `bundle exec rake db:test:prepare`, and then was able to run the specs with `bundle exec rake`.

I thought when you ran `rake db:setup`, and didn't specify a RAILS_ENV, it created both the development and test databases if they didn't exists, so I'm not sure why the test database wasn't created when I ran the setup script.

**Comment by leesharma** [comment]
Good catch! 👍 We should this to `bin/setup` to handle the test database.

Is everyone comfortable with `rake db:test:prepare`? I know it was deprecated in 4.1.0 and then undeprecated shortly thereafter, but it looks like it's here to stay now.

**Comment by leesharma** [comment]
Since no one’s grabbed this one yet, I’ll take care of it.

This definitely has nothing to do with hacktoberfest ending today. :jack_o_lantern:
