### ISSUE TITLE
Add a name field to work_sites

### ISSUE THREAD

**Issue by glroman** [rubyforgood/habitat_humanity#107]
Add a `name` field to the **work_sites** table which can be used when displaying and selecting **work_sites**.  On **work_site** creation, the `name` field should be required and unique.  The `address` field should remain required and be shown when viewing **work_site** details.

**Comment by glroman** [comment]
I'll tackle this; thanks.  It's blocking #55.

**Comment by bjmllr** [comment]
@glazomaniac Do work sites have names?

**Comment by glroman** [comment]
Sorry, I didn't realize the question was still outstanding.  From reading the material on the http://www.habitat-nola.org site, I saw these and thought they must have names for the various projects:

* Musicians’ Village
* Faith Build
* Jimmy and Rosalynn Carter Work Project
* Blitz Build
* America Street

I can try finishing #55 without this and then change it to accommodate names if/when we hear back that it's OK.

**Comment by bjmllr** [comment]
Looking at the database, right now we have 3 separate work sites on America Street. You can them all at https://habitat-nola-signin.herokuapp.com/ by checking the work site dropdown.

**Comment by glroman** [comment]
Got it.  So it's not looking good for the `name` idea.  Wonder if they'd want to group things by project?  If so, then something like "America Street, WS001" might be useful.  The problem I see now is that if their active list ever gets to be large, the drop-downs get unwieldy.  And over time, active + inactive gets large and the only application key into that list is the address.

**Comment by glazomaniac** [comment]
We sometimes have names for special builds or projects, but yeah, it's better if we just do this all by address. Thanks for the thought, though!

**Comment by glazomaniac** [comment]
We'll never be building more than 10-20 addresses at a time--our staff just isn't big enough for that. Usually it's around 10 or 12. So it shouldn't be a problem regarding the dropdowns if the inactive sites are able to be removed from them when we're  done.

**Comment by glroman** [comment]
@glazomaniac Thanks for the feedback; I'm closing this issue.
