### ISSUE TITLE
js error prevents running specs with js enabled

### ISSUE THREAD

**Issue by crawfoal** [rubyforgood/habitat_humanity#109]
I was trying to write a spec with `js: true`, and got this error:

```
Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: null is not an object (evaluating 'wrapper.querySelector')
       TypeError: null is not an object (evaluating 'wrapper.querySelector')
```

I think this error occurs on the admin sign in page, and is because `signature.js` runs on all pages, but the admin sign in page doesn't have the signature field. I don't see this error on the admin dashboard, but I think that might have to do with the administrate gem.

**Comment by AliSchlereth** [comment]
Hi @leesharma & @crawfoal,
  I'd like to take a crack at fixing this assuming it still needs work?  I've read CONTRIBUTING.md and will do my best to follow your guidelines.  This sounds like a great project!
