### ISSUE TITLE
scale signatures in the Signature Report to a consistent size

### ISSUE THREAD

**Issue by bjmllr** [rubyforgood/habitat_humanity#116]
In the Signatures Report (`/admin/signatures_report`) there are slight differences in the size of the signature images, and the images frequently don't fit inside the horizontal margins of the report. We should display them in a consistent size. The org has requested that we display them smaller, and many signatures already in the database are around 1300 x 150, so something like 650 x 75 might be more manageable. It would be nice if we could keep the aspect ratio, but it's not essential.

**Comment by JeanJoeris** [comment]
Hi, just wanted to let you know that @danbroadbent and I wanted to add this feature. I hope that is ok, we'll let you know if we have any questions
