### ISSUE TITLE
In feature specs, check for phantomjs rather than environment variable

### ISSUE THREAD

**Issue by crawfoal** [rubyforgood/habitat_humanity#133]
The feature specs that require JavaScript currently looks for an environment variable:

```ruby
skip 'PhantomJS 2+ required' unless ENV['RAILS_SPEC_JS']
```

If instead we check for the presence and version of the phantomjs executable, then it will run by default when possible. When someone is new to the project, they don't have to set up an environment variable to get the JS feature specs running.

**Comment by bjmllr** [comment]
The skips were added to prevent these tests from running under CI, since there was no (easy) way to use PhantomJS 2 under Travis at the time. If things have since improved, then we could remove the skips.
