### ISSUE TITLE
email addresses

### ISSUE THREAD

**Issue by glazomaniac** [rubyforgood/habitat_humanity#17]
Hi, all,

We'd love to be able to thank you when this is all over. If you want to provide your email addresses, we'd love to send a follow up. I promise we won't put you on our mailing lists unless you explicitly ask to be! Just pass your email addresses along if you wanna be on the "thank you" list!

Thanks,

Sally

**Comment by pat** [comment]
Sure 😄 - you can reach me on pat@freelancing-gods.com.

**Comment by bjmllr** [comment]
@glazomaniac can we close this?

**Comment by glazomaniac** [comment]
yes.
