### ISSUE TITLE
signatures report

### ISSUE THREAD

**Issue by bjmllr** [rubyforgood/habitat_humanity#3]
The org would like to have a summary of shift events for the past week (sign-ins and sign-outs with and without signatures).

**Comment by scooter-dangle** [comment]
So far, we're saying this isn't just a summary of time worked, it should actually include all of the signatures associated with the times worked.

**Comment by scooter-dangle** [comment]
I'm assuming we want the data ordered by date, but that may be incorrect.

Within each day I'd probably order signatures by work site and then group by shift.

@bjmllr:
Question: For Shift summary calculations like "duration" and "duration_including_breaks" (not necessarily those names), do we want that to be calculated in the Shift model or in the report? (I'm assuming for now that we're always intending to calculate that on read and not permanently store it somewhere...)

**Comment by bjmllr** [comment]
Since we can do the calculation with only the `ShiftEvent`s associated with a given shift, I think it's fine to make those instance methods of `Shift`.

**Comment by scooter-dangle** [comment]
K cool. In that case will work on adding those to the model as part of this branch.

**Comment by bjmllr** [comment]
still polishing, but generally completed in #18
