### ISSUE TITLE
administrative activities

### ISSUE THREAD

**Issue by bjmllr** [rubyforgood/habitat_humanity#5]
The org needs a way to allow admins to securely access sign-in and sign-out data, such as a web-based control panel.

* [x] admin auth
* [x] a way to provide a spreadsheet of collected signature data
* [x] a way to control form access by time ( #4 )

**Comment by pat** [comment]
Are we expecting multiple admins needing access? Is a single shared username and password an option (perhaps via HTTP Authentication)? Or will separate accounts (Devise et al) be useful?

**Comment by bjmllr** [comment]
The staff isn't huge so a single account might be an option. @glazomaniac any thoughts?

**Comment by glazomaniac** [comment]
I thought I answered this! A single shared username is fine. Just make it "Habitat."

**Comment by bjmllr** [comment]
We went with multiple accounts after all (one can be named "Habitat" :smile_cat: ). provided in #21
