### ISSUE TITLE
Only authorized individuals should be able to create admin accounts.

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#62]
Currently anyone can create an admin account via `users/sign_up`, which gives them access to reports containing sensitive information. Only valid individuals should be able to create these accounts/view these reports.

**Comment by leesharma** [comment]
I can think of two ways to solve this: invitations or account approval. Either way, we'll need to initialize the project with a first admin user.

If we want to go the invitations route, I've had success using the [`devise_invitable`](https://github.com/scambra/devise_invitable) gem in the past.

**Comment by bjmllr** [comment]
The org is happy with a single user, it's just that devise is built for multiple users, and the team wanted to use devise for other reasons. If needed, we can create users at the console, once public signups are disabled.

`devise_invitable` sounds pretty awesome.

**Comment by bjmllr** [comment]
I disabled new user registration in 06c77c9ebbf6a578506997ef3c2a7f6c56201861 and b705fc79115f696d3791dc77f620408627505906 in the simplest way I could find and pushed the result to heroku. Feel free to undo those changes if they don't mesh.

**Comment by leesharma** [comment]
I used your changes and went a bit further (removing it from the model and adding a rake task).
