### ISSUE TITLE
Administrate views are not mobile-friendly

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#91]
The administrate views aren't mobile-responsive–on mobile, the sidebar takes up nearly the full screen, and the buttons/fields stack and shrink. The actual tables are scrollable, but they're tough to get to. Here's an image illustrating this:

![broken admin views](https://cloud.githubusercontent.com/assets/814638/17124126/dc75af4e-52b6-11e6-887b-a6d6c315ab15.png)

Per [this Administrate issue](https://github.com/thoughtbot/administrate/issues/360), it seems to be a known issue.

**Comment by leesharma** [comment]
Depending on how likely it is that someone would use this on a phone, I can think of two options:

- Quick hack fix (fixing the width and allowing people to zoom in or something) if we don't expect much mobile use
- Actual solution (hamburger menu on mobile, sidebar moves to a top menu, or something more usable), which will probably take more time but be more usable

Any other ideas? How much of an issue do you all think this is?

**Comment by glazomaniac** [comment]
The quick hack fix is fine.

**Comment by leesharma** [comment]
This issue has been claimed by @darwin-s-walters.

**Comment by salimane** [comment]
any update on the mobile-responsive–on mobile ?
