### ISSUE TITLE
Missing steps in Quick Start Guide

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#95]
This issue comes from #94 (Problems 1 & 2)

**System:** Fedora 23
### Current Behavior

The [Quick Start Guide](https://github.com/rubyforgood/habitat_humanity#quick-start) in the README describes some of the required dependencies of the project:

> By the end of this section, you should have the project and dependencies installed on your local system. For information on how to contribute, see Contributing.
> 
> You need:
> - Ruby 2.3
> - Rails 4.2.x
> - Postgres 9.5 (May be changed by team later)
> - PhantomJS (brew install phantomjs on macOS or read instructions)
> 
> Basically you need Git, Ruby and Rails. If you have Git, Ruby and Postgres in some version or another you're probably set. But:
> - If you're working on a virgin Windows machine, you're best off going with the RailsInstaller at http://railsinstaller.org.
> - If you have a virgin Mac OSX machine, just follow the directions in https://gorails.com/setup/osx/10.11-el-capitan.

However, note that this doesn't mention a Javascript runtime–required for Rails development–and that we only include links/advice for OS X and Windows.
### Desired Behavior

1) We should be clear that a javascript runtime (preferably Node) is required for development. 

2) Ideally, we should also include some links/assistance on how to install the project dependencies (postgres, node, ruby, rails, etc) for people with Linux machines.

I think README.md is the best place for this since we have no setup instructions in the wiki.

**Comment by JeanJoeris** [comment]
@danbroadbent and I are happy to add some documentation about needing node installed along with some resources for installation.
