### ISSUE TITLE
`bin/setup` generates an error

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#97]
This issue comes from #94 (Problem 5)

**System:** Fedora 23

### Current Behavior

`bin/setup` generates an error.

This command:

```bash
system 'touch tmp/restart.txt'
```

Yields this error:

```bash
touch: cannot touch 'tmp/restart.txt': No such file or directory
```

### Desired Behavior

`bin/setup` should run successfully without error

**Comment by leesharma** [comment]
We have three suggested solutions for this bug:

- From glroman (does anyone know his GitHub username?):
  
  Add a line to `bin/setup`:
  ```ruby
  system '[[ ! -d tmp ]] && mkdir tmp' # Add this
  system 'touch tmp/restart.txt'
  ```

- From @bjmllr:

  Use `FileUtils` instead of `system` for file operations:

  ```ruby
  FileUtils.rm_f 'log/*'
  FileUtils.rm_rf 'tmp/cache'
  ...
  FileUtils.mkdir('tmp') unless File.directory?('tmp')
  FileUtils.mkdir_p 'tmp'
  FileUtils.touch 'tmp/restart.txt'
  ```

- From @leesharma:

  Change the line to:
  ```ruby
  system 'mkdir -p tmp && touch tmp/restart.txt'
  ```
  (since `mkdir` is more recognizable for non-bash programmers than `[[]]`)

Lots of options!

**Comment by crawfoal** [comment]
I can work on this issue. It will be my first open source contribution, and I have a couple questions:

1. If I cloned the repo via instructions on the Getting Started page (`git clone http://github.com/rubyforgood/habitat_humanity`), then is that the same as a fork? Or do I need to do something different?

2. I've reproduced the issue on Ubuntu 16.04, but I don't have anything set up with Fedora right now... would it be okay to work on this issue using Ubuntu, or should I make a Fedora USB to work from?

**Comment by glroman** [comment]
Hi @crawfoal, thanks for taking up this issue.  I believe that if you can get it working on Ubuntu that it will also work on Fedora: both distros should be failing in the same way for this issue.

As for cloning: that won't work as we're using the Forking Workflow Model.  I found [the description  here](https://www.atlassian.com/git/tutorials/comparing-workflows/) helpful.

**Comment by crawfoal** [comment]
@glroman Thanks, that article was really helpful.

Since I'll only be changing the setup script, I won't be creating a test for this, right?

**Comment by glroman** [comment]
Right. Either it runs clean or it doesn't.
