### ISSUE TITLE
NoMethodError when running reports

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#99]
This issue comes from #94 (Problem 8)

**System:** Fedora 23

### Current Behavior

NoMethodError when running reports

```
NoMethodError (undefined method `occurred_at' for nil:NilClass):
  app/models/shift.rb:69:in `block in breaks_duration'
  app/models/shift.rb:68:in `each'
  lib/csv_report_generator.rb:21:in `generate_report'
  app/reports/concerns/csv_generatable.rb:45:in `to_csv'
  app/controllers/hours_reports_controller.rb:11:in `block (2 levels) in show'
  app/controllers/hours_reports_controller.rb:10:in `show'
```

#### Steps to Reproduce

Suspect this happens when EndBreakDateTime is nil.

### Desired Behavior

Creating a report should return a reasonable default instead of blowing up with a `NoMethodError`.

**Comment by leesharma** [comment]
This issue isn't fully fleshed out because I didn't have time to actually investigate it.

Could someone investigate this further and fill out **Steps to Reproduce** and **Desired Behavior** (ie–what method with which arguments causes this, what is a reasonable default, etc)? Neither is really actionable at the moment.

**Comment by bjmllr** [comment]
To reproduce, create a shift that has an event for the start of a break, but no event for the end of that break, then try to export HoursReport to CSV over a time-span including all the events of the shift. Rather than 500'ing, I think we should report the problem to the user so that they can ignore the cell or row, or try to fix the data. Perhaps the CSV generator could put some sort of message that explains the problem in the appropriate cells.

**Comment by crawfoal** [comment]
I can start working on this.

When a volunteer has forgotten to sign back in from a break, what should we put in the `duration_without_breaks` field of the report? Maybe something like "Error: missing info."?

Should we also send an email to a volunteer who has forgotten to sign back in from a break? Maybe make this a separate issue?

**Comment by crawfoal** [comment]
Also, would just putting that in the report be enough to grab their attention?

**Comment by bjmllr** [comment]
@crawfoal Thanks for picking this up!

A volunteer won't be able to see the report, so if we want to contact them directly, we'd send them a separate email. Admins can contact volunteers and make corrections to records by hand if needed, so I'd prioritize giving the admins better visibility ahead of directly contacting volunteers.
